# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#
# 2026-02 手工校准：UUID 与子卷对应 98x 重装后的实际布局（lsblk -f 核实）
# 注意：/nix 实际挂载在 home 子卷上（store 数据在 home 子卷内），
#       空的 nix 子卷存在但未使用，不要改成 subvol=nix！

{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/510c59f1-0328-48cb-a5e6-332839e68bba";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/510c59f1-0328-48cb-a5e6-332839e68bba";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" ];
    };

  # 与当前运行系统一致：/nix 也挂 home 子卷
  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/510c59f1-0328-48cb-a5e6-332839e68bba";
      fsType = "btrfs";
      options = [ "subvol=home" "noatime" "compress=zstd" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5A37-60F5";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/2113f0a6-8723-43f8-b51d-c79384febca8"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp8s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
